server:
  port: 8081
  servlet:
    context-path: /32106
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: checker
    password: cs307proj
    driver-class-name: org.postgresql.Driver
